title: Zain Zhenyuan Ruan
logo: http://zainryan.github.io/photo.jpg
description: "zainruan [at] csail [dot] mit [dot] edu<br><br> Office 32-G978B,<br> 32 Vassar Street, <br>Cambridge, MA 02139"
google_analytics:
theme: jekyll-theme-minimal
